version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: adriel/pokedex
    ports:
      - "3000:3000"
    environment:
      - PG_DB=pokedex
      - PG_USER=postgres
      - PG_PASSWORD=admin
      - PG_HOST=node_db
      - NODE_ENV=development
    depends_on:
      - node_db
    restart: always

  node_db:
    container_name: node_db
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pokedex
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}
